server.port=8081
spring.application.name=theatre-service

# Database
spring.datasource.url=jdbc:h2:mem:theatre_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 Console
spring.h2.console.enabled=true

# JPA configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#For feign calls use retry configuration
#resilience4j.retry.instances.showService.maxAttempts=3
#resilience4j.retry.instances.showService.waitDuration=5s